name: Ejemplo CI/CD

on:
  push:

jobs:
  inicio:
    runs-on: windows-latest
    steps:
      - name: Mostrar texto
        run: echo "Paso para clonar repositorio a GitHub Actions"
      - name: Checkout
        uses: actions/checkout@v4.2.2

  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Mostrar texto
        run: echo "Construir"

      - name: Instalar PHP y Composer en Windows
        run: |
          choco install php --version=8.1 -y
          choco install composer -y
          php -v
          composer --version

      - name: Instalar MySQL Server
        run: |
          choco install mysql57 -y --ignore-checksums
          echo "MySQL instalado correctamente"

      - name: Iniciar MySQL y configurar root
        run: |
          net start mysql
          echo "Esperando que MySQL inicie..."
          timeout /t 10
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"

      - name: Crear base de datos
        run: |
          mysql -u root -proot -e "CREATE DATABASE lumen_db; SHOW DATABASES;"

  test:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Mostrar texto
        run: echo "Ejecutar pruebas"

  deploy:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: Mostrar texto
        run: echo "Desplegar aplicación"
